eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-service
server:
  port: 9000

#zuul:
#  routes:
#    blog:
#        path: /spring_cloud-pzs12ixk
#        url: https://www.w3cschool.cn/spring_cloud/spring_cloud-pzs12ixk.html

zuul:
  routes:
    api:
        path: /**
        serviceId: service-hi